config/routes.rb
Rails.application.routes.draw do
	root :to => "articles#index"
  get 'articles/index'

  get 'articles/profile'

  get 'articles/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ActiveRecord::Base

    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  	@articles
  end

  def profile
  	@articles
  end

  def contact
  	@articles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/contact.html.erb
<div class="row">
       <div class="col-md-4">
        <div class="poto">
           <h1>Riku Kiranatama</h1>  
           <img class="img-responsive img-circle poto-propil" src="img/riku.png">
        </div>
      </div> 

      <div class="col-md-8">
        <div class="data-diri">
        <form class="form-horizontal">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                  <input type="email" class="form-control" id="inputEmail3" placeholder="Email Anda">
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Mesages</label>
                <div class="col-sm-10">
                  <textarea class="form-control" rows="3" placeholder="Mesages Anda"></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input class="btn btn-default" type="submit" value="Submit">
                </div>
            </div>
        </form>    
            
        </div>
      </div>

      </div>
    </div>

app/views/articles/index.html.erb
<div id="first-slider">
    <div id="carousel-example-generic" class="carousel slide carousel-fade">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <!-- Item 1 -->
            <div class="item active slide1">
                <div class="row">
                    <div class="container">
                        <div class="col-md-3 "><p class="keterangan">Langit Bintang Bintang</p></div>
                    </div>
                </div>
             </div> 
            <!-- Item 2 -->
            <div class="item slide2">
                <div class="row">
                    <div class="container">
                        <div class="col-md-3 "><p class="keterangan">Rumput Hijau</p></div>
                    </div>
                </div>
            </div>
            <!-- Item 3 -->
            <div class="item slide3">
                <div class="row">
                    <div class="container">
                        <div class="col-md-3 "><p class="keterangan">Pegunungan Batu</p></div>
                    </div>
                </div>
            </div>
            <!-- Item 4 -->
            <div class="item slide4">
               <div class="container">
                        <div class="col-md-3 "><p class="keterangan">Lagi-lagi langit</p></div>
                </div>
            </div>
            <!-- End Item 4 -->
    
        </div>
        <!-- End Wrapper for slides-->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i><span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i><span class="sr-only">Next</span>
        </a>
    </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <div class="bio">
           <p>Hello saya Riku dan saya saat ini akan lulus dari kuliah, salam kenal ya. Berikut contoh dari hasil design grafik yang saya buat :) </p> 
        </div>
      </div>
      <div class="col-md-4">
        <div class="bio2">
            <table class="table">
                <tr>
                    <td class="bio-huruf">Facebook</td>
                    <td class="bio-huruf">:</td>
                    <td class="bio-huruf">riku@mail.com</td>
                </tr>
                <tr>
                    <td class="bio-huruf">Twitter</td>
                    <td class="bio-huruf">:</td>
                    <td class="bio-huruf">riku@mail.com</td>
                </tr>
                <tr>
                    <td class="bio-huruf">Telpon</td>
                    <td class="bio-huruf">:</td>
                    <td class="bio-huruf">022-232392</td>
                </tr>
                <tr>
                    <td class="bio-huruf">Alamat</td>
                    <td class="bio-huruf">:</td>
                    <td class="bio-huruf">Jl.Harapan Bangsa no.23, Bandung, Indonesia</td>
                </tr>
            </table> 
        </div>
      </div> 
      </div>
    </div>

app/views/articles/profile.html.erb
<div class="row">
       <div class="col-md-4">
        <div class="poto">
           <h1>Riku Kiranatama</h1>  
           <img class="img-responsive img-circle poto-propil" src="/img/riku.png">
        </div>
      </div> 

      <div class="col-md-8">
        <div class="data-diri">
            <table class="table table-striped">
                <tr>
                    <td class="bio-huruf">Nama</td>
                    <td class="bio-huruf">:</td>
                    <td class="bio-huruf">Riku Kranatama</td>
                </tr>
                <tr>
                    <td class="bio-huruf">Tempat, Tanggal Lahir </td>
                    <td class="bio-huruf">:</td>
                    <td class="bio-huruf">Bandung, 7 Oktober 1989</td>
                </tr>
                <tr>
                    <td class="bio-huruf">Jenis Kelamin</td>
                    <td class="bio-huruf">:</td>
                    <td class="bio-huruf">Pria</td>
                </tr>
                <tr>
                    <td class="bio-huruf">Alamat Domisili</td>
                    <td class="bio-huruf">:</td>
                    <td class="bio-huruf">Jl.Soekarno Hatta no.104</td>
                </tr>
            </table>
            
        </div>
      </div>

      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rendy3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="" />
<meta name="author" content="http://themesplay.com" />
<!-- css -->
<link href="/css/bootstrap.min.css" rel="stylesheet" />
<link rel="/stylesheet" href="simple-line-icons/css/simple-line-icons.css">
<link href="/css/fancybox/jquery.fancybox.css" rel="stylesheet">
<link href="/css/jcarousel.css" rel="stylesheet" />
<link href="/css/flexslider.css" rel="stylesheet" />
<link href="/js/owl-carousel/owl.carousel.css" rel="stylesheet">
<link href="/css/style.css" rel="stylesheet" />
<link rel="stylesheet" href="http://cdn.bootcss.com/animate.css/3.5.1/animate.min.css">
  </head>

  <body>
  <div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
    <div class="container-fluid">
        <div class="navbar-header"><a class="navbar-brand" href="home.htm">Training Bootstrap</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-right">
                </li>
                <li><a href="/">Home</a>
                </li>
                <li><a href="<%=articles_profile_path%>">Profile</a>
                </li>
                <li><a href="contact.htm">Contact </a>
                </li>
            </ul>
        </div>
    </div>
    </div> 
    <%= yield %>

<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
<!-- javascript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery.js"></script>
<script src="/js/jquery.easing.1.3.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.fancybox.pack.js"></script>
<script src="/js/jquery.fancybox-media.js"></script> 
<script src="/js/portfolio/jquery.quicksand.js"></script>
<script src="/js/portfolio/setting.js"></script>
<script src="/js/jquery.flexslider.js"></script>
<script src="/js/animate.js"></script>
<script src="/js/custom.js"></script>
<script src="/js/owl-carousel/owl.carousel.js"></script> 

</script>
</body>
</html>